name: wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  responsive_sizer: ^3.1.0
  cupertino_icons: ^1.0.2
  easy_search_bar: ^2.3.1 #filter search
  flutter_native_splash: any
  http: any
  get: any
  intl: any
  expansion_tile_card: ^2.0.0
  flutter_sms_inbox: ^1.0.2
  permission_handler: any
  substring_highlight: ^1.0.33
  flutter_launcher_icons: ^0.12.0
  shared_preferences: ^2.0.18

  introduction_screen: ^3.1.4
  collection: ^1.16.0

  syncfusion_flutter_datepicker: "20.4.44"
  vibration: ^1.7.6
  telephony: ^0.2.0
  tutorial_coach_mark: ^1.2.4
  awesome_notifications: ^0.7.4+1
  google_pay_passes: ^1.0.0

  #pay: ^1.1.0
  #google_sign_in: ^6.0.2
  #googleapis: ^4.0.0
  #googleapis_auth: ^1.1.0

  #walletconnect_qrcode_modal_dart: ^0.3.1
  #public_address_wallet: ^0.0.6
  #wallet_connect: ^1.0.4 #62
  #wallet_connect_v2: ^1.0.0 #9
  #walletconnect_dart: ^0.0.11


  #eth_sig_util: ^0.0.9
  #flutter_inappwebview: ^5.7.2+3
  #web3dart: ^2.5.0

  #stream_channel: ^2.1.1
  #wallet: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


assets:
  - images/a_dot_burr.jp



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter_native_splash:
  color: "#0a1227"
  image: assets/images/logo.png
  fullscreen: true
  andoid: true
  ios: true

flutter:
  assets:
    - assets/images/
  uses-material-design: true

